name: cocoicons
description: The COCO icon pack with - +600 icons available for your flutter project.
version: 0.1.0
repository: https://github.com/Mastersam07/cocoicons
homepage: https://github.com/Mastersam07/cocoicons

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
   - family: cocoline
     fonts:
      - asset: fonts/cocoline.ttf
   - family: cocobold
     fonts:
      - asset: fonts/cocobold.ttf
   - family: cocoduotone
     fonts:
      - asset: fonts/cocoduotone.ttf
